### PR TITLE
feat: allow redis keyword configuration

### PR DESCRIPTION
**Pull request by wu-clan**
please review.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@wu-clan can you also add to README about the new usage? https://github.com/pycasbin/redis-adapter#simple-example

**Comment by wu-clan** [comment]
I'm not sure how to add it, for normal users it works the same way as before

For special users, it now allows any Redis configuration parameter to be used

**Comment by hsluoyz** [comment]
@wu-clan how people know there's such option without looking at source code?

> For special users, it now allows any Redis configuration parameter to be used

Do they know this?

**Comment by wu-clan** [comment]
@hsluoyz please review.

**Pull request merged**
